CREATE TABLE ide(

cUF VARCHAR(50),
cNF VARCHAR(50),
natOp VARCHAR(50),
indPag VARCHAR(50),
mob VARCHAR(50),
serie VARCHAR(50),
nNF VARCHAR(50),
dEmi VARCHAR(50),
dSaiEnt VARCHAR(50),
tpNF VARCHAR(50),
idDest VARCHAR(50),
cMunFG VARCHAR(50),
tpImp VARCHAR(50),
tpEmis VARCHAR(50),
cDV VARCHAR(50),
tpAmb VARCHAR(50),
finNFe VARCHAR(50),
indFinal VARCHAR(50),
indPres VARCHAR(50),
procEmi VARCHAR(50),
verProc VARCHAR(50),
ID_ide INT PRIMARY KEY AUTO_INCREMENT
);

SELECT * FROM ide;

DROP TABLE ide;

CREATE TABLE emit (

CNPJ VARCHAR(50),
xNome VARCHAR(50),
xFant VARCHAR(50),
xLgr VARCHAR(50),
nro VARCHAR(50),
xBairo VARCHAR(50),
cMun VARCHAR(50),
xMun VARCHAR(50),
UF VARCHAR(50),
CEP VARCHAR(50),
cPais VARCHAR(50),
xPais VARCHAR(50),
fone VARCHAR(50),
IE VARCHAR(50),
CRT VARCHAR(50),
ID_emit INT PRIMARY KEY AUTO_INCREMENT
);

DROP Table emit;

SELECT * FROM emit;

CREATE TABLE dest(

CNPJ VARCHAR(50),
xNome VARCHAR(50),
xLgr VARCHAR(50),
nro VARCHAR(50),
xBairro VARCHAR(50),
cMun VARCHAR(50),
xMun VARCHAR(50),
UF VARCHAR(50),
CEP VARCHAR(50),
cPais VARCHAR(50),
xPais VARCHAR(50),
fone VARCHAR(50),
indIEDest VARCHAR(50),
IE_dest VARCHAR(50),
ID_dest INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE dest;

SELECT * FROM dest;


CREATE TABLE entrega (

CNPJ VARCHAR(50),
xLgr VARCHAR(50),
nro VARCHAR(50),
xBairro VARCHAR(50),
cMun VARCHAR(50),
xMun VARCHAR(50),
UF VARCHAR(50),
ID_entrega INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE entrega;

SELECT * FROM entrega;

CREATE TABLE produto(

cProd VARCHAR(50),
cEAN VARCHAR(50),
xProd VARCHAR(50),
NCM VARCHAR(50),
CFOP VARCHAR(50),
uCom VARCHAR(50),
qCom VARCHAR(50),
vUnCom VARCHAR(50),
vProd VARCHAR(50),
cEANTrib VARCHAR(50),
uTrib VARCHAR(50),
qTrib VARCHAR(50),
vUnTrib VARCHAR(50),
indTot VARCHAR(50),
ID_produto INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE produto;

SELECT * FROM produto;

CREATE TABLE  imposto(

orig VARCHAR(50),
CST VARCHAR(50),
ID_imposto INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE imposto;

SELECT * FROM imposto;


CREATE TABLE IPI(

cEnq VARCHAR(50),
CST VARCHAR(50),
vBC VARCHAR(50),
pIPI VARCHAR(50),
vIPI VARCHAR(50),
ID_IPI INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE IPI;

SELECT * FROM IPI;

CREATE TABLE PIS (

CST VARCHAR(50),
vBC VARCHAR(50),
pPIS VARCHAR(50),
vPIS VARCHAR(50),
ID_PIS INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE PIS;

SELECT * FROM PIS;

CREATE TABLE COFINS(

CST VARCHAR(50),
vBC VARCHAR(50),
pCOFINS VARCHAR(50),
vCOFINS VARCHAR(50),
ID_COFINS INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE COFINS;

SELECT * FROM COFINS;

CREATE TABLE total (

vBC VARCHAR(50),
vICMS VARCHAR(50),
vICMSDeson VARCHAR(50),
vBCST VARCHAR(50),
vST VARCHAR(50),
vProd VARCHAR(50),
vFrete VARCHAR(50),
vSeg VARCHAR(50),
vDesc VARCHAR(50),
vII VARCHAR(50),
vIPI VARCHAR(50),
vPIS VARCHAR(50),
vCOFINS VARCHAR(50),
vOutro VARCHAR(50),
vNF VARCHAR(50),
vTotTrib VARCHAR(50),
ID_TOTAL INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE total;

SELECT * FROM total;

CREATE TABLE transptda(

CNPJ VARCHAR(50),
xNome VARCHAR(50),
xEnder VARCHAR(50),
xMun_transptda  VARCHAR(50),
UF_transptda VARCHAR(50),
ID_transptda INT PRIMARY KEY AUTO_INCREMENT
);


DROP TABLE transptda;

SELECT * FROM transptda;

CREATE TABLE veic_transptda(

placa_veicTransptda VARCHAR(50),
UF_veicTransptda VARCHAR(50),
ID_veic INT PRIMARY KEY AUTO_INCREMENT
);

SELECT * FROM veic_transptda;

DROP TABLE veic_transptda;

CREATE TABLE vol(

qVol VARCHAR(50),
nVol VARCHAR(50),
pesoL VARCHAR(50),
pesoB VARCHAR(50),
ID_vol INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE vol;

SELECT * FROM vol;

CREATE TABLE cobr(

nFat VARCHAR(50),
nVol VARCHAR(50),
vLiq VARCHAR(50),
ID_cobr INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE cobr;

SELECT * FROM cobr;

CREATE TABLE dup(

nDu VARCHAR(50),
dVenc VARCHAR(50),
vDup VARCHAR(50),
ID_dup INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE dup;

SELECT * FROM dup;

CREATE TABLE infAdic(

infCpl VARCHAR(500),
IND_infAdic INT PRIMARY KEY AUTO_INCREMENT
);

DROP TABLE infAdic;

SELECT * FROM infAdic;





